# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 249ce7a986674275e6b23ba6543af4ebda8412b0cb5cde81cc9a8077ad77d531efe9e49b5f4c28a35943ef9a8715ea180f0ea0cbc28d6cd574622b700a4e63e4

test:
  secret_key_base: ccc00474747e71e3f7e541e51f407be25c8012107d5d33d492eb4c7852d7ae17d343fe7090820b8c68f0156515833ab90b86e6970eab3d248f824ab23a881dca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
